{{- if .Values.apiGateway.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-nebula.fullname" . }}-api-gateway
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        {{- include "project-nebula.labels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
    spec:
      serviceAccountName: {{ include "project-nebula.serviceAccountName" . }}
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "project-nebula.apiGateway.jwtSecretName" . }}
                  key: jwtSecret
{{- end }}
