{{- if .Values.apiGateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-nebula.fullname" . }}-api-gateway
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
{{- end }}
