{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "project-nebula.fullname" . }}
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.ingress.hostname }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "project-nebula.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "project-nebula.fullname" . }}-api-gateway
                port:
                  number: {{ .Values.apiGateway.service.port }}
{{- end }}
