{{- if .Values.security.networkPolicy.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-traffic
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - {key: app.kubernetes.io/component, operator: In, values: [frontend, api-gateway]}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          # This label should match your Ingress controller pods
          app.kubernetes.io/name: ingress-nginx
{{- end }}
