{{- if .Values.orderService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-nebula.fullname" . }}-order-service
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: order-service
{{- end }}
