{{- if .Values.postgresql.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "project-nebula.fullname" . }}-postgresql
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "project-nebula.fullname" . }}-postgresql-headless
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "project-nebula.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - postgresql
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.secrets.existingSecret | default (printf "%s-postgresql" (include "project-nebula.fullname" .)) }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.postgresql.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
