{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-nebula.fullname" . }}-postgresql
  labels:
    {{- include "project-nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql
    # This selector assumes you have a way to label the primary pod.
    # For a real HA setup, this would be managed by an operator.
    statefulset.kubernetes.io/pod-name: {{ include "project-nebula.fullname" . }}-postgresql-0
{{- end }}
